# Javascript Node CircleCI 2.0 configuration file
#
# See https://circleci.com/docs/2.0/language-javascript/ for more details.
#
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    # Specify the version you desire here.
    - image: circleci/node:12

    # Specify service dependencies here if necessary.
    # CircleCI maintains a library of pre-built images,
    # documented in https://circleci.com/docs/2.0/circleci-images/

commands:
  install:
    steps:
      - checkout
      - run: yarn

jobs:
  test:
    <<: *defaults
    steps:
      - install
      - run: yarn test
      - run: yarn lint-css
      - run: yarn lint-ts
      - run: yarn format-check
      - run: yarn link-check-exclude

  test_full:
    <<: *defaults
    steps:
      - install
      - run: yarn test
      - run: yarn lint-css
      - run: yarn lint-ts
      - run: yarn format-check
      - run: yarn link-check
      - run: yarn link-check-exclude

workflows:
  version: 2

  commit:
    jobs:
      - test

  daily:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - test_full
