name: DVC Link Check
on: deployment_status

jobs:
  run:
    name: Run Link Checker
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:

    - uses: actions/checkout@v2

    - name: Run the link checker
      id: check
      uses: "iterative/link-check.action@master"
      with:
        rootURL: "${{ github.event.deployment.payload.web_url }}"
        linkExcludePatternFiles: "./scripts/exclude-links.txt"
        fileExcludePatternFiles: "./scripts/exclude-files.txt"
        fileIncludePatterns: "{.github,content,src}/**/*.{css,js,jsx,md,tsx,ts,json}"

    - uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Link Check
        status: completed
        conclusion: ${{ steps.check.outputs.conclusion }}
        output: ${{ steps.check.outputs.output }}
