name: DVC Link Check
on: deployment_status

jobs:
  run:
    name: Run Link Checker
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:

    - uses: actions/checkout@v2

    - name: Run the link checker
      id: check
      inputs:
        baseURL: "${{ github.event.deployment_status.target_url }}"
      runs:
        using: 'node12'
        main: 'scripts/link-check/action.js'

    - uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Link Check
        status: completed
        conclusion: ${{ steps.check.outputs.conclusion }}
        output:
          summary: ${{ steps.check.outputs.summary }}
          text_description: ${{ steps.check.outputs.description }}
