name: Link Check All
on:
  deployment:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    name: Link Check All Job
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Run the link check script
      id: check
      uses: "iterative/link-check.action@master"
      with:
        source: "filesystem"
        configFile: "./.linkcheckrc.json"

    - uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Link Check All Check
        status: completed
        conclusion: ${{ steps.check.outputs.conclusion }}
        output: ${{ steps.check.outputs.output }}
